### ISSUE TITLE
pre-flight checks should finish for all contexts before starting installation

### ISSUE THREAD

**Issue by hr1sh1kesh** [infracloudio/krius#33]
If you use the spec. 

```
---
clusters:
- name: kind-cluster1
  type: prometheus
  data:
    install: true
    name: promcluster1
    namespace: monitoring
    mode: sidecar
    objStoreConfig: bucketcluster1
- name: kind-cluster2
  type: prometheus
  data:
    install: false
    name: prom
    namespace: monitoring-sidecar
    mode: sidecar
    objStoreConfig: bucketcluster2
objStoreConfigslist:
- name: bucketcluster1
  type: s3
  config:
    bucket: krius
    endpoint: "192.168.0.104:9000"
    accessKey: minioadmin
    secretKey: minioadmin
  bucketweb:
    enabled: true
- name: bucketcluster2
  type: s3
  config:
    bucket: krius
    endpoint: "192.168.0.104:9000"
    accessKey: minioadmin
    secretKey: minioadmin
  bucketweb:
    enabled: false
```

Notice that the second cluster `kind-cluster2` does not need install `install: false`. In that case the pre-flight checks should check if the namespace exists or not before installing prometheus on `kind-cluster1`

Essentially all pre-flight checks for all contexts should happen before the installation begins.
